### ISSUE TITLE
Update podspec on cocoapods repo

### ISSUE THREAD

**Issue by AYastrebov** [RxSwiftCommunity/RxViewModel#53]
Currently, version 4.0.0 is available if installing from cocoapods repo.
Please, consider updating the podspec

**Comment by freak4pc** [comment]
Well, only one person who can fix that ;-) 

👉 @esttorhe 👈

**Comment by esttorhe** [comment]
Hi @AYastrebov; thanks for reporting this.

Any chance you could run `pod spec update`?
I just checked on `CocoaPods` website and locally via `pod search RxViewModel` and was able to find `5.0.0` (see images below).

![screen shot 2017-08-14 at 11 30 10](https://user-images.githubusercontent.com/2642850/29266291-90a5cb14-80e4-11e7-83f8-74c2dcf1ec9b.png)
![screen shot 2017-08-14 at 11 33 25](https://user-images.githubusercontent.com/2642850/29266293-924f55ca-80e4-11e7-94c2-76a0a7ca20d4.png)


Would be great if you could do this and get back to me because it could be a misconfiguration on my local env.

🙇  Thanks

**Comment by AYastrebov** [comment]
@esttorhe thanks for quick response!
As I see, issue 54 is not applied, so currently I am unable to use the latest version (only 4.0.0 is available).

**Comment by esttorhe** [comment]
@ayastrebov so it doesn't show even after running 
`pod spec update`?

**Comment by freak4pc** [comment]
@esttorhe I think his point is that because of the hard dependency that will be resolved in 5.0.1, he cannot install 5.0.0 without breaking his dependency on RxSwift 3.6.1. 

I'm gonna take of this RN :)

**Comment by esttorhe** [comment]
👌
Got it 🙇

–
Esteban Torres
CraftKollective Co-Founder

Phone:  (+49)0162-4190-543
Skype:  esteban.a.torres.hernandez
Twitter:  @esttorhe

**Comment by freak4pc** [comment]
v5.0.1 has been released @AYastrebov
